spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: http://localhost:8088
            predicates:
              - Path= /api/customers/**
          - id: r2
            uri: http://localhost:8089
            predicates:
              - Path= /api/products/**